version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Porta para conexões AMQP
      - "15672:15672"   # Porta para a interface de gerenciamento
    volumes:
        - ./definitions.json:/etc/rabbitmq/definitions.json:ro
        - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_LOAD_DEFINITIONS: "true"

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    ports:
      - "8081:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev
  
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --save 1 1 --loglevel warning
    restart: always
    depends_on:
      - sysctl_init
  
  sysctl_init:
    image: alpine:latest
    container_name: sysctl_init
    command: sh -c "sysctl -w vm.overcommit_memory=1"
    privileged: true
    entrypoint: ["/bin/sh", "-c", "sysctl -w vm.overcommit_memory=1 && tail -f /dev/null"]
    
volumes:
  redis_data:
    driver: local