spring:
  application:
    name: msclientes

  datasource:
    url: jdbc:h2:mem:bancoclientes
    driver-class-name: org.h2.Driver
    username: admin
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      path: /h2
      enabled: true

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.2:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    