spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 5000  # 5 segundos
        response-timeout: 10s  # 10 segundos
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/avaliadorcreditorealm
          jwk-set-uri: http://localhost:8081/realms/avaliadorcreditorealm/protocol/openid-connect/token

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    io.github.resilience4j: DEBUG

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
