name: Análise SonarCloud

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - eurekaserver
          - msavaliadorcredito
          - mscartoes
          - msclientes
          - mscloudgateway
    steps:
      - name: Checar código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.0
        with:
          projectBaseDir: ArqMicroservices/${{ matrix.service }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets['SONAR_PROJECT_KEY_'${{ matrix.service }}] }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
